# Generated by Django 3.0.7 on 2021-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0003_auto_20210502_1128'),
        ('sig', '0001_initial'),
        ('recruitment', '0008_auto_20210502_1128'),
        ('project', '0010_auto_20210502_1128'),
        ('event', '0004_auto_20210502_1128'),
        ('account', '0010_sig_website_talk_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxcore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='core',
            name='user',
        ),
        migrations.DeleteModel(
            name='SIG',
        ),
        migrations.AlterField(
            model_name='user',
            name='batch_of',
            field=models.IntegerField(blank=True, default=2023),
        ),
        migrations.DeleteModel(
            name='AuxCore',
        ),
        migrations.DeleteModel(
            name='Core',
        ),
    ]
