# Generated by Django 4.2 on 2023-05-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_first_name'),
        ('account', '0020_auto_20230508_2128'),
    ]

    operations = [
    ]
