# Generated by Django 3.0.7 on 2020-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='isdone',
            new_name='isDone',
        ),
        migrations.AddField(
            model_name='round',
            name='reg_link',
            field=models.TextField(default=''),
        ),
    ]
