# Generated by Django 3.0.7 on 2020-07-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200722_1106'),
        ('recruitment', '0002_auto_20200723_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='sigs',
        ),
        migrations.AddField(
            model_name='round',
            name='sig',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.SIG'),
            preserve_default=False,
        ),
    ]
