# Generated by Django 3.0.7 on 2020-07-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20200723_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='reg_link',
        ),
    ]
