# Generated by Django 3.0.7 on 2020-07-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auxcore'),
        ('recruitment', '0004_remove_round_reg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SIG'),
        ),
    ]
