# Generated by Django 3.0.7 on 2020-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_sighead'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
