# Generated by Django 3.0.7 on 2020-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_sig_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sig',
            name='summary',
            field=models.TextField(default='SIG Summary'),
        ),
    ]
