# Generated by Django 3.0.7 on 2020-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200722_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='reg_url',
            field=models.TextField(default=''),
        ),
    ]
