# Generated by Django 3.0.7 on 2020-07-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200723_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
