# Generated by Django 3.0.7 on 2020-07-23 11:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20200722_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_time', models.DateTimeField()),
                ('isdone', models.BooleanField(default=False)),
                ('sigs', models.ManyToManyField(to='account.SIG')),
            ],
        ),
    ]
