# Generated by Django 3.0.7 on 2021-05-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
        ('recruitment', '0007_auto_20200727_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sig.SIG'),
        ),
    ]
