# Generated by Django 3.0.7 on 2021-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20210502_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
