# Generated by Django 3.0.7 on 2021-08-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_round_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
