# Generated by Django 3.0.7 on 2021-08-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0002_auto_20210502_1341'),
        ('recruitment', '0010_auto_20210802_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='link',
        ),
        migrations.CreateModel(
            name='RegLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sig.SIG')),
            ],
        ),
    ]
