# Generated by Django 3.0.7 on 2021-08-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_auto_20210802_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglink',
            name='descriptionSIG',
            field=models.TextField(default='SIG description', max_length=200),
        ),
    ]
