# Generated by Django 3.0.7 on 2021-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_reglink_descriptionsig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglink',
            name='descriptionSIG',
            field=models.TextField(default='SIG description'),
        ),
    ]
