# Generated by Django 3.0.7 on 2021-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_sig_website_talk_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('summary', models.TextField(default='SMP Summary')),
                ('file_url', models.URLField(default='#', max_length=250)),
                ('img_url', models.URLField(default='https://res.cloudinary.com/dogygnvzl/image/upload/v1618295702/logo_2_ratj0j.png')),
                ('sigs', models.ManyToManyField(to='account.SIG')),
            ],
        ),
    ]
