# Generated by Django 3.0.7 on 2021-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smp',
            name='softwares',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='smp',
            name='file_url',
            field=models.URLField(default='https://youtu.be/dQw4w9WgXcQ', max_length=250),
        ),
    ]
