# Generated by Django 3.0.7 on 2020-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200722_1106'),
        ('project', '0006_project_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sigs',
            field=models.ManyToManyField(related_name='project_sig', to='account.SIG'),
        ),
    ]
