# Generated by Django 3.0.7 on 2021-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carousel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='type',
            field=models.CharField(choices=[('1', 'Mobile'), ('2', 'Desktop')], default='2', max_length=1),
        ),
    ]
