# Generated by Django 3.0.7 on 2021-05-02 11:28

from django.db import migrations, models
import website.helperFunctions


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210320_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='url',
        ),
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default=website.helperFunctions.default_carousel_image_path, upload_to=website.helperFunctions.carousel_upload_path),
        ),
    ]
