# Generated by Django 3.0.7 on 2020-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20200726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
