# Generated by Django 3.0.7 on 2020-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20200727_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(),
        ),
    ]
