# Generated by Django 3.0.7 on 2020-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_core_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='summary',
            field=models.TextField(default='Sig summary'),
        ),
    ]
