# Generated by Django 3.0.7 on 2020-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auxcore'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='test_url',
            field=models.TextField(default=''),
        ),
    ]
