# Generated by Django 3.0.7 on 2020-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_sig_test_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='website_talk_url',
            field=models.TextField(default=''),
        ),
    ]
