# Generated by Django 3.0.7 on 2022-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squareonelb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squareoneuser',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
