# Generated by Django 3.0.7 on 2021-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sig',
            name='website_talk_url',
            field=models.URLField(default=''),
        ),
    ]
