# Generated by Django 3.0.3 on 2020-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sig',
            new_name='sigs',
        ),
    ]
