# Generated by Django 3.0.3 on 2020-07-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200702_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members',
            new_name='editable_by',
        ),
    ]
