# Generated by Django 3.1.14 on 2023-01-20 09:52

from django.db import migrations, models
import website.helperFunctions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default=website.helperFunctions.default_gallery_image_path, upload_to=website.helperFunctions.gallery_image_upload_path)),
            ],
        ),
    ]
