# Generated by Django 3.1.14 on 2023-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimages',
            old_name='image',
            new_name='imageLink',
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
