# Generated by Django 3.1.14 on 2023-01-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20230120_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImages',
            new_name='GalleryImage',
        ),
    ]
