# Generated by Django 3.0.7 on 2023-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20230120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='imageLink',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
