# Generated by Django 3.0.7 on 2023-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20230203_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='imageLink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
