# Generated by Django 3.1.14 on 2023-02-12 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20230203_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 8, 58, 54, 57769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='event',
            field=models.CharField(default='', max_length=200),
        ),
    ]
