# Generated by Django 3.0.7 on 2020-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_isfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default='Project Summary'),
        ),
    ]
