# Generated by Django 3.0.7 on 2020-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_url',
            field=models.TextField(default=''),
        ),
    ]
