# Generated by Django 3.0.7 on 2024-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotlandyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellcolor',
            name='color',
            field=models.CharField(max_length=3),
        ),
    ]
