# Generated by Django 3.0.7 on 2024-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotlandyard', '0003_auto_20240929_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellcolor',
            name='blue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cellcolor',
            name='green_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cellcolor',
            name='red_count',
            field=models.IntegerField(default=0),
        ),
    ]
