# Generated by Django 3.0.7 on 2024-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotlandyard', '0004_auto_20240929_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellcolor',
            name='color',
            field=models.CharField(default='white', max_length=7),
        ),
    ]
