# Generated by Django 3.0.7 on 2020-07-12 18:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_of_participants',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='publicity_message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
