# Generated by Django 3.0.7 on 2021-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200712_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.TextField(default=''),
        ),
    ]
