# Generated by Django 3.0.7 on 2021-05-02 11:28

from django.db import migrations, models
import website.helperFunctions


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
        ('event', '0003_auto_20210211_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default=website.helperFunctions.default_event_poster_path, upload_to=website.helperFunctions.event_poster_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='sigs',
            field=models.ManyToManyField(related_name='sigs', to='sig.SIG'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='MS Teams', max_length=100),
        ),
    ]
