# Generated by Django 3.0.7 on 2022-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('yearPassed', models.IntegerField(default=0)),
                ('firstYear', models.IntegerField(default=0)),
                ('secondYear', models.IntegerField(default=0)),
                ('thirdYear', models.IntegerField(default=0)),
                ('fourthYear', models.IntegerField(default=0)),
            ],
        ),
    ]
