# Generated by Django 3.0.7 on 2022-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('firstYear', models.IntegerField(default=0)),
                ('secondYear', models.IntegerField(default=0)),
                ('thirdYear', models.IntegerField(default=0)),
                ('fourthYear', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='firstYear',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='fourthYear',
        ),
        migrations.RemoveField(
            model_name='team',
            name='secondYear',
        ),
        migrations.RemoveField(
            model_name='team',
            name='thirdYear',
        ),
    ]
