# Generated by Django 3.0.7 on 2022-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obscura', '0003_attempt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='firstYearQuestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='fourthYearQuestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='secondYearQuestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='thirdYearQuestion',
            field=models.IntegerField(default=0),
        ),
    ]
