# Generated by Django 3.0.7 on 2021-05-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxcore',
            name='email',
        ),
        migrations.RemoveField(
            model_name='core',
            name='email',
        ),
    ]
