# Generated by Django 3.0.7 on 2022-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210509_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxcore',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='core',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
